Repository neithere/argh, pull requests merged in 2023-02, with the labels that each got.

#87 Added autocommand to the "similar projects" list
  docs/similar.rst
Labels: component-docs

#160 docs: add Read the Docs config
  .readthedocs.yml
Labels: component-docs

#163 Ensure full test coverage
  CHANGES
  src/argh/assembling.py
  src/argh/completion.py
  src/argh/constants.py
  src/argh/decorators.py
  src/argh/dispatching.py
  src/argh/exceptions.py
  src/argh/helpers.py
  src/argh/interaction.py
  src/argh/io.py
  src/argh/utils.py
  tests/base.py
  tests/test_assembling.py
  tests/test_completion.py
  tests/test_decorators.py
  tests/test_dispatching.py
  tests/test_integration.py
  tests/test_interaction.py
  tests/test_regressions.py
  tests/test_utils.py
  tox.ini
Labels: chore

#166 Lint: configure the Bandit tool
  .pre-commit-config.yaml
  pyproject.toml
  src/argh/assembling.py
  src/argh/utils.py
  tests/test_assembling.py
Labels: chore

#173 chore: publishing to prod PyPI
  .github/workflows/lint-and-test.yml
  .github/workflows/release.yml
  MANIFEST.in
  Makefile
  pyproject.toml
  tox.ini
Labels: component-packaging
